<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        * { box-sizing: border-box; }
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #1f2937;
            font-size: 11px;
            margin: 0;
            padding: 0;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            border-bottom: 3px solid #b8860b;
            padding-bottom: 14px;
            margin-bottom: 18px;
        }
        .brand-name {
            font-size: 20px;
            font-weight: bold;
            color: #b8860b;
            letter-spacing: 1px;
            margin: 0 0 4px 0;
        }
        .brand-sub { color: #6b7280; font-size: 10px; line-height: 1.5; margin: 0; }
        .doc-title {
            text-align: right;
            text-transform: uppercase;
            letter-spacing: 2px;
            color: #b8860b;
            font-size: 14px;
            font-weight: bold;
        }
        .doc-meta { text-align: right; font-size: 10px; color: #6b7280; margin-top: 2px; }
        .report-type {
            display: inline-block;
            margin-top: 6px;
            padding: 3px 10px;
            border-radius: 3px;
            background: #f3f4f6;
            color: #374151;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        table.items { width: 100%; border-collapse: collapse; margin-top: 16px; }
        table.items th {
            background: #f3f4f6;
            text-align: left;
            text-transform: uppercase;
            font-size: 9px;
            letter-spacing: 1px;
            color: #6b7280;
            padding: 8px;
            border-bottom: 2px solid #b8860b;
        }
        table.items td { padding: 8px; border-bottom: 1px solid #e5e7eb; color: #374151; }
        table.items td.num, table.items th.num { text-align: right; }
        .empty { margin-top: 24px; padding: 24px; text-align: center; color: #9ca3af; background: #f9fafb; border-radius: 4px; }
        .footer {
            margin-top: 24px;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
            font-size: 9px;
            color: #9ca3af;
            text-align: center;
            line-height: 1.6;
        }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <p class="brand-name">{{ $hotel['hotel_name'] ?? 'Pampanga Home Suites' }}</p>
            <p class="brand-sub">{{ $hotel['hotel_address'] ?? '' }}</p>
            <p class="brand-sub">{{ $hotel['hotel_phone'] ?? '' }}{{ !empty($hotel['hotel_phone']) && !empty($hotel['hotel_email']) ? '  |  ' : '' }}{{ $hotel['hotel_email'] ?? '' }}</p>
        </div>
        <div>
            <p class="doc-title">{{ ucfirst($type) }} Report</p>
            <p class="doc-meta">{{ $from }} — {{ $to }}</p>
            <p class="report-type">Generated {{ now()->format('M d, Y H:i') }}</p>
        </div>
    </div>

    @if(count($rows) > 0)
        <table class="items">
            <thead>
                <tr>
                    @foreach($headers as $header)
                        <th>{{ $header }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($rows as $row)
                    <tr>
                        @foreach($row as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="empty">No data available for the selected period.</div>
    @endif

    <div class="footer">
        Generated by the {{ $hotel['hotel_name'] ?? 'Pampanga Home Suites' }} management system.
    </div>
</body>
</html>
